FROM python:3.11 

# Install SSH client
RUN apt-get update && apt-get install -y openssh-client


#set enviroment variables
ENV PYTHONUNBUFFERED=1


#set the working directory
WORKDIR /app


#copy requirements.txt file 
COPY requirements.txt  /app/requirements.txt


#Install python dependencies
RUN pip install -r requirements.txt


#copy the aplication to the working directory
COPY . /app


#Start the SSH tunnel
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]


